From: _encodeObject
| [<GHIssue 0x60800005f0b0>/MTLModel encodeWithCoder:<NSKeyedArchiver 0x608000112510>]
|   +[GHIssue/MTLModel modelVersion]
|   +[GHIssue/MTLModel encodingBehaviorsByPropertyKey]
|     +[GHIssue/MTLModel propertyKeys]
|   +[GHIssue/MTLModel transitoryPropertyKeys]
|     +[GHIssue/MTLModel generateAndCacheStorageBehaviors]
|       +[GHIssue/MTLModel propertyKeys]
|       +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"URL"]
|       +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"title"]
|       +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"name"]
|       +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"user"]
|   +[GHIssue/MTLModel permanentPropertyKeys]
|   [<GHIssue 0x60800005f0b0> getName]
| From: -[MTLModel description]
| +[GHIssue/MTLModel permanentPropertyKeys]
| From: -[NSObject(NSKeyValueCoding) valueForKey:]
| [<GHIssue 0x60800005f0b0> getName]
