| From: -[ViewController tapButton:]
| +[MTLJSONAdapter modelOfClass:<GHIssue 0x1011408f0> fromJSONDictionary:<__NSDictionaryI 0x60000007df40> error:0x7fff5eb4a660]
|   [<MTLJSONAdapter 0x610000241980> initWithModelClass:<GHIssue 0x1011408f0>]
|     +[GHIssue JSONKeyPathsByPropertyKey]
|     +[GHIssue/MTLModel propertyKeys]
|       +[GHIssue/MTLModel enumeratePropertiesUsingBlock:<__NSStackBlock__ 0x7fff5eb49c40>]
|         +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"URL"]
|         +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"title"]
|         +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"user"]
|         +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"name"]
|         +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"hash"]
|           +[MTLModel storageBehaviorForPropertyWithKey:@"hash"]
|         +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"superclass"]
|           +[MTLModel storageBehaviorForPropertyWithKey:@"superclass"]
|         +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"description"]
|           +[MTLModel storageBehaviorForPropertyWithKey:@"description"]
|         +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"debugDescription"]
|           +[MTLModel storageBehaviorForPropertyWithKey:@"debugDescription"]
|     +[MTLJSONAdapter valueTransformersForModelClass:<GHIssue 0x1011408f0>]
|       +[GHIssue/MTLModel propertyKeys]
|       +[GHIssue URLJSONTransformer]
|       +[MTLJSONAdapter transformerForModelPropertiesOfClass:<NSString 0x1015a4ad8>]
|       +[MTLJSONAdapter transformerForModelPropertiesOfClass:<NSString 0x1015a4ad8>]
|       +[GHIssue userJSONTransformer]
|         +[MTLJSONAdapter dictionaryTransformerWithModelClass:<GHUser 0x101140a30>]
|   [<MTLJSONAdapter 0x610000241980> modelFromJSONDictionary:<__NSDictionaryI 0x60000007df40> error:0x7fff5eb4a660]
|     +[GHIssue/MTLModel propertyKeys]
|     [<MTLJSONAdapter 0x610000241b00> initWithModelClass:<GHUser 0x101140a30>]
| From: +[MTLModel storageBehaviorForPropertyWithKey:]
| +[MTLModel storageBehaviorForPropertyWithKey:@"hash"]
| From: +[MTLModel storageBehaviorForPropertyWithKey:]
| +[MTLModel storageBehaviorForPropertyWithKey:@"superclass"]
| From: +[MTLModel storageBehaviorForPropertyWithKey:]
| +[MTLModel storageBehaviorForPropertyWithKey:@"description"]
| From: +[MTLModel storageBehaviorForPropertyWithKey:]
| +[MTLModel storageBehaviorForPropertyWithKey:@"debugDescription"]
| From: -[MTLJSONAdapter initWithModelClass:]
| +[MTLJSONAdapter valueTransformersForModelClass:<GHUser 0x101140a30>]
| From: +[MTLJSONAdapter valueTransformersForModelClass:]
| +[MTLJSONAdapter transformerForModelPropertiesOfObjCType:"q"]
| From: +[MTLJSONAdapter valueTransformersForModelClass:]
| +[MTLJSONAdapter transformerForModelPropertiesOfClass:<NSString 0x1015a4ad8>]
| From: +[MTLJSONAdapter valueTransformersForModelClass:]
| +[MTLJSONAdapter transformerForModelPropertiesOfObjCType:"q"]
| From: +[MTLJSONAdapter valueTransformersForModelClass:]
| +[MTLJSONAdapter transformerForModelPropertiesOfClass:<NSString 0x1015a4ad8>]
| From: __73+[MTLJSONAdapter(ValueTransformers) dictionaryTransformerWithModelClass:]_block_invoke
| [<MTLJSONAdapter 0x610000241b00> modelFromJSONDictionary:<__NSDictionaryI 0x60000007dd80> error:0x7fff5eb49d98]
| From: -[MTLJSONAdapter modelFromJSONDictionary:error:]
| +[GHIssue/MTLModel modelWithDictionary:<__NSDictionaryM 0x610000241860> error:0x7fff5eb4a660]
|   [<GHIssue 0x60000005ca40>/MTLModel initWithDictionary:<__NSDictionaryM 0x610000241860> error:0x7fff5eb4a660]
|     [<GHIssue 0x60000005ca40>/MTLModel init]
|     [<GHIssue 0x60000005ca40> setURL:<NSURL 0x610000090310>]
|     [<GHIssue 0x60000005ca40> setTitle:@"百度"]
|     [<GHIssue 0x60000005ca40> setName:@"李俊峰"]
|   [<GHIssue 0x60000005ca40> setUser:<GHUser 0x61800005c890>]
| From: -[MTLJSONAdapter modelFromJSONDictionary:error:]
| [<GHIssue 0x60000005ca40>/MTLModel validate:0x7fff5eb4a660]
|   +[GHIssue/MTLModel propertyKeys]
|   [<GHIssue 0x60000005ca40> getName]
| From: -[MTLModel description]
| +[GHIssue/MTLModel permanentPropertyKeys]
|   +[GHIssue/MTLModel generateAndCacheStorageBehaviors]
|     +[GHIssue/MTLModel propertyKeys]
|     +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"URL"]
|     +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"title"]
|     +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"name"]
|     +[GHIssue/MTLModel storageBehaviorForPropertyWithKey:@"user"]
| From: -[NSObject(NSKeyValueCoding) valueForKey:]
| [<GHIssue 0x60000005ca40> getName]
2016-11-23 14:11:41.704 MantleDemo[18844:1172014] issue: <GHIssue: 0x60000005ca40> {
    URL = "www.baidu.com";
    name = "\U674e\U4fca\U5cf0";
    title = "\U767e\U5ea6";
    user = "<GHUser: 0x61800005c890> {\n    age = 0;\n    gender = \"\\U7537\";\n    name = \"\\U674e\\U4fca\\U5cf0\";\n    success = 0;\n}";
}
